version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      # install dependencies first (on 1 machine)
      - cypress/install
      # now run tests
      - cypress/run:
          # give this job a custom name for clarity
          name: 'cypress-project'
          requires:
            # use previously installed dependencies
            # to avoid installing them on each machine running tests
            - cypress/install
          record: true
          parallel: true # run tests in parallel
          parallelism: 3 # use 3 CircleCI machines
          group: "CircleCI Test"
          start: 'npm start' # start server before running tests
          wait-on: "http://localhost:3000"
          command: 'npx cypress run --record --key=6624b18b-9581-4f57-b060-fbc73ed34e27 --parallel'
