version: 0.2

# AWS CodeBuild Batch configuration
# https://docs.aws.amazon.com/codebuild/latest/userguide/batch-build-buildspec.html


phases:
  install:
    runtime-versions:
      nodejs: latest
  pre_build:
    commands:
      - npm run cy:verify
      - npm run cy:info
  build:
    # Per https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-env-vars.html
    # use $CODEBUILD_INITIATOR as it provides the entity that started the build
    # which is unique and can be used as the --ci-build-id for the Cypress Dashboard
    commands:
        - npm run start
        - npm run test