name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: "Tests"
        uses: cypress-io/github-action@v4
        with:
          command: npm cy:start-server-cy:run:headless
          parallel: true
